# Generated by Django 4.2.13 on 2024-05-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000)),
                ('category', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('units_in_stock', models.IntegerField()),
                ('brand', models.CharField(max_length=255)),
            ],
        ),
    ]
